create_venv: &create_venv
  name: create virtualenv
  command: |
    python -m venv venv

chmod_usr_share: &chmod_usr_share
  name: chmod usr share to be world read/write/exec
  command: |
    sudo chmod a+rwx /usr/share

install_project: &install_project
  name: install project in venv
  command: |
    . venv/bin/activate
    pip install /tmp/workspace/amdgpu_fan-*tar.gz

test_project: &test_project
  name: run tests
  command: |
    . venv/bin/activate
    pip install pytest
    cd tests
    python3 -m pytest

init_pypirc: &init_pypirc
  name: init .pypirc
  command: |
    echo -e "[pypi]" >> ~/.pypirc
    echo -e "username = chestm007" >> ~/.pypirc
    echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

package_and_upload: &package_and_upload
  name: package and upload
  command: |
    sudo pip install twine
    twine upload /tmp/workspace/amdgpu_fan-*.tar.gz

build_artifact: &build_artifact
  name: build artifact
  command: |
    sed -i "s/PROJECTVERSION/`python get_build_version.py`/g" setup.py
    python setup.py sdist

update_aur_amdgpu_fan_dev: &update_aur_amdgpu_fan_dev
  name: clone amdgpu-fan github aur repo
  command: |
    git clone ssh+git@github.com:chestm007/aur-amdgpu-fan-dev
    cd aur-amdgpu-fan-dev
    sed -i "s/^pkgver=\d+.\d+.\d+$/pkgver=$(CIRCLE_TAG)/g" PKGBUILD
    git add PKGBUILD
    git commit -a -m "version bump to $(CIRCLE_TAG)"
    git push

test_steps: &test_steps
  steps:
    - attach_workspace:
        at: /tmp/workspace
    - checkout
    - run:
        <<: *create_venv
    - run:
        <<: *chmod_usr_share
    - run:
        <<: *install_project
    - run:
        <<: *test_project

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          <<: *build_artifact
      - persist_to_workspace:
          root: dist
          paths: amdgpu_fan-*.tar.gz

  python3.6:
    docker:
      - image: circleci/python:3.6.8-stretch
    working_directory: ~/repo
    <<: *test_steps
  python3.7:
    docker:
      - image: circleci/python:3.7.3-stretch
    working_directory: ~/repo
    <<: *test_steps

  deploy:
    docker:
      - image: circleci/python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          <<: *init_pypirc
      - run:
          <<: *package_and_upload

  update_downstream_aur_package:
    docker:
      - image: circleci/python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 5d:27:86:9d:37:22:36:7e:1b:3c:a0:1d:64:03:48:18
      - run:
          <<: *update_aur_amdgpu_fan_dev



workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - python3.6:
          requires:
            - build
      - python3.7:
          requires:
            - build
      - deploy:
          requires:
            - python3.6
            - python3.7
      - update_downstream_aur_package:
          requires:
            - deploy
          filters:
            branches:
              only: master
            tags:
              only: /^\d+.\d+.\d+$/

